### ISSUE TITLE
Extension now working?

### ISSUE THREAD

**Issue by asgeirtj** [pionxzh/chatgpt-exporter#230] opened 2024-04-12 19:20 UTC
Seems to be broken right now

**Comment by pionxzh** [comment] 2024-04-12 19:28
It still works on my side. Can you try export any format and take a screenshot of console?

**Comment by asgeirtj** [comment] 2024-04-12 19:31
Sure

<img width="1028" alt="image" src="https://github.com/pionxzh/chatgpt-exporter/assets/27446620/cdd1401e-dc7e-4326-b4d3-6686590c421e">

**Comment by pionxzh** [comment] 2024-04-12 20:50
Are you using team plan?

**Comment by asgeirtj** [comment] 2024-04-12 20:51
No, personal

**Comment by pionxzh** [comment] 2024-04-12 21:54
got it. I will check further.

**Comment by IlyaRice** [comment] 2024-04-16 07:16
I tested some things. 
Team account - not working.
Personal paid account - not working.
Free account from Chrome Incognito mode - not working.

Issue persists with all JSON formats, Markdown, HTML, Export All.
Screenshot export is working.

Here some details:
[Initial extension errors after loading the page](https://i.imgur.com/CxvUTy2.png)
[Markdown export error](https://i.imgur.com/6IQ0wV0.png)
[JSON export error](https://i.imgur.com/hsp4s0a.png)
[Export All error](https://i.imgur.com/rzmuYWT.png)

P.S. I'm glad to help with resolving this issue. Do you have telegram messenger?

**Comment by pionxzh** [comment] 2024-04-16 07:40
oh wow, thanks for the detailed report. I suspect they are ab testing some changes that haven't been applied to my account.

**Comment by pionxzh** [comment] 2024-04-16 07:42
wait I can reproduce it now.

**Comment by IlyaRice** [comment] 2024-04-16 08:06
If needed, I have dozens of accounts.  I am ready to provide them for the common cause.

**Comment by pionxzh** [comment] 2024-04-16 18:54
May I know your OS and browser? It works on my window 11 + chrome latest. But failed on Mac + Chrome latest.

**Comment by pionxzh** [comment] 2024-04-17 03:12
It works ok on my Mac now... so confusing...

**Comment by IlyaRice** [comment] 2024-04-17 04:06
I have the same: window 11 + chrome latest. 
And what is the most strange, that the extension is working today on some accounts.
It still sends some error in console, but all functions are working properly right now. 

Tested json, md, html and "export all" again:
Free acc - all works
Team acc - all works
Plus acc - nothing works

The thing is that team and plus are the same acc, but different workspaces.
I have some insights on cause of issue, but I'm not proficient enough to test and even to locate it right.

**Comment by pionxzh** [comment] 2024-04-17 04:13
I'm using Plus account. 🤔 

I feel this is either an authentication issue or Cloudflare robot detection blocking. You can also share other findings here, we can find out the root cause together.

**Comment by IlyaRice** [comment] 2024-04-17 08:12
### About errors with a Plus account on an account with two workspaces:
The most curious thing is that when I open the "Export all" window, the list of dialogues from the Team workspace is loaded, despite the fact that I have switched to my personal workspace.
[Team workspace "Export All" dialogues](https://i.imgur.com/l3AYpZ9.png)
[Personal workspace "Export All" dialogues](https://i.imgur.com/HFA5dMQ.png)
Before that, the extension loaded the correct list of dialogs for export in each workspace.

It looks like they've changed something in the principle of authentication and dialog storage in accounts with two workspaces. Because an attempt to load JSON returns a 
/different error (404) to the console than the previous time.
[Trying export JSON in personal workspace](https://i.imgur.com/WTj3Mda.png)

**Comment by pionxzh** [comment] 2024-04-17 08:24
May I know how you switch between team and personal account? will it refresh after switching?

The extension is still assuming you are on the team plan, so it brings the team token to the API. I guess the server don't want to leak if this id exists or not for security reasons, so it returns a 404.

**Comment by IlyaRice** [comment] 2024-04-17 08:43
> May I know how you switch between team and personal account? will it refresh after switching?

[Here is how](https://i.imgur.com/BLRzaW9.gif)

**Comment by pionxzh** [comment] 2024-04-17 10:55
the `v4-2023-04-27` request is where the extension gets your `Chatgpt-Account-Id`. We alr integrated it.

**Comment by pionxzh** [comment] 2024-04-17 11:23
It's possible that the extension use the `Chatgpt-Account-Id` wrongly because I'm not that familiar with how it works. I added the support purely based on public information and some code snippets on github.

What do you mean  two `Chatgpt-Account-Id` ? You got two?

**Comment by IlyaRice** [comment] 2024-04-17 11:47
<details>
  <summary>Do you need this content?</summary>

  ```json
  {
      "accounts": {
          "5ea18f8d-9e19-xxxx-xxxx-14777052ec60": {
              "account": {
                  "account_user_role": "account-owner",
                  "account_user_id": "user-3qbcXxxxxxxxy6VutWUNfdz__5ea18f8d-9e19-xxxx-xxxx-14777052ec60",
                  "processor": {
                      "a001": {
                          "has_customer_object": true
                      },
                      "b001": {
                          "has_transaction_history": false
                      },
                      "c001": {
                          "has_transaction_history": false
                      }
                  },
                  "account_id": "5ea18f8d-9e19-xxxx-xxxx-14777052ec60",
                  "organization_id": "org-nGA6vlYRQOxxxxx6uP8meS2ZGD",
                  "is_most_recent_expired_subscription_gratis": false,
                  "has_previously_paid_subscription": true,
                  "name": "Ricery",
                  "profile_picture_id": null,
                  "profile_picture_url": null,
                  "structure": "workspace",
                  "plan_type": "team",
                  "is_deactivated": false,
                  "promo_data": {}
              },
              "features": [
                  "arkose_enabled",
                  "arkose_enabled_for_subscription",
                  "beta_features",
                  "bizmo_settings",
                  "breeze_available",
                  "browsing_available",
                  "chat_preferences_available",
                  "chatgpt_ios_attest",
                  "chatgpt_team_plan",
                  "code_interpreter_available",
                  "d3_controls",
                  "d3_editor",
                  "d3_editor_gpts",
                  "disable_model_upsell",
                  "disable_upgrade_ui",
                  "gizmo_reviews",
                  "gizmo_support_emails",
                  "invite_referral",
                  "memory_history_enabled",
                  "memory_model_override",
                  "memory_model_override_check",
                  "mfa",
                  "model_ab_use_v2",
                  "model_switcher",
                  "new_plugin_oauth_endpoint",
                  "paragen_mainline_alternative",
                  "plugins_available",
                  "privacy_policy_nov_2023",
                  "shareable_links",
                  "starter_prompts",
                  "system_message2",
                  "targeted_replies",
                  "thumbs_down_only",
                  "use_o11y",
                  "user_settings_announcements",
                  "workspace_gpt_custom_actions",
                  "workspace_share_links"
              ],
              "entitlement": {
                  "subscription_id": "345abe93-cda5-xxxx-xxxx-94fb97656275",
                  "has_active_subscription": true,
                  "subscription_plan": "chatgptteamplan",
                  "expires_at": "2024-05-14T19:44:12+00:00",
                  "billing_period": "monthly"
              },
              "last_active_subscription": {
                  "subscription_id": "345abe93-cda5-xxxx-xxxx-94fb97656275",
                  "purchase_origin_platform": "chatgpt_web",
                  "will_renew": true
              },
              "is_eligible_for_yearly_plus_subscription": false
          },
          "0d1b6707-3119-xxxx-xxxx-596c869db2cd": {
              "account": {
                  "account_user_role": "account-owner",
                  "account_user_id": "user-3qbcXxxxxxxxy6VutWUNfdz__0d1b6707-3119-xxxx-xxxx-596c869db2cd",
                  "processor": {
                      "a001": {
                          "has_customer_object": true
                      },
                      "b001": {
                          "has_transaction_history": false
                      },
                      "c001": {
                          "has_transaction_history": false
                      }
                  },
                  "account_id": "0d1b6707-3119-xxxx-xxxx-596c869db2cd",
                  "organization_id": null,
                  "is_most_recent_expired_subscription_gratis": false,
                  "has_previously_paid_subscription": true,
                  "name": null,
                  "profile_picture_id": null,
                  "profile_picture_url": null,
                  "structure": "personal",
                  "plan_type": "free",
                  "is_deactivated": false,
                  "promo_data": {}
              },
              "features": [
                  "arkose_enabled",
                  "arkose_enabled_for_subscription",
                  "beta_features",
                  "bizmo_settings",
                  "breeze_available",
                  "browsing_available",
                  "chat_preferences_available",
                  "chatgpt_ios_attest",
                  "chatgpt_team_plan",
                  "code_interpreter_available",
                  "d3_controls",
                  "d3_editor",
                  "d3_editor_gpts",
                  "dalle_3",
                  "gizmo_reviews",
                  "gizmo_support_emails",
                  "invite_referral",
                  "memory_history_enabled",
                  "memory_model_override",
                  "memory_model_override_check",
                  "mfa",
                  "model_ab_use_v2",
                  "model_switcher",
                  "new_plugin_oauth_endpoint",
                  "paragen_mainline_alternative",
                  "plugins_available",
                  "privacy_policy_nov_2023",
                  "shareable_links",
                  "starter_prompts",
                  "targeted_replies",
                  "thumbs_down_only",
                  "use_o11y",
                  "user_settings_announcements"
              ],
              "entitlement": {
                  "subscription_id": "e5833ba0-ec68-xxxx-xxxx-a221eb5e6c37",
                  "has_active_subscription": false,
                  "subscription_plan": "chatgptplusplan",
                  "expires_at": "2024-01-29T20:56:58+00:00",
                  "billing_period": null
              },
              "last_active_subscription": {
                  "subscription_id": "e5833ba0-ec68-xxxx-xxxx-a221eb5e6c37",
                  "purchase_origin_platform": "chatgpt_web",
                  "will_renew": false
              },
              "is_eligible_for_yearly_plus_subscription": false
          },
          "default": {
              "account": {
                  "account_user_role": "account-owner",
                  "account_user_id": "user-3qbcXxxxxxxxy6VutWUNfdz__0d1b6707-3119-xxxx-xxxx-596c869db2cd",
                  "processor": {
                      "a001": {
                          "has_customer_object": true
                      },
                      "b001": {
                          "has_transaction_history": false
                      },
                      "c001": {
                          "has_transaction_history": false
                      }
                  },
                  "account_id": "0d1b6707-3119-xxxx-xxxx-596c869db2cd",
                  "organization_id": null,
                  "is_most_recent_expired_subscription_gratis": false,
                  "has_previously_paid_subscription": true,
                  "name": null,
                  "profile_picture_id": null,
                  "profile_picture_url": null,
                  "structure": "personal",
                  "plan_type": "free",
                  "is_deactivated": false,
                  "promo_data": {}
              },
              "features": [
                  "arkose_enabled",
                  "arkose_enabled_for_subscription",
                  "beta_features",
                  "bizmo_settings",
                  "breeze_available",
                  "browsing_available",
                  "chat_preferences_available",
                  "chatgpt_ios_attest",
                  "chatgpt_team_plan",
                  "code_interpreter_available",
                  "d3_controls",
                  "d3_editor",
                  "d3_editor_gpts",
                  "dalle_3",
                  "gizmo_reviews",
                  "gizmo_support_emails",
                  "invite_referral",
                  "memory_history_enabled",
                  "memory_model_override",
                  "memory_model_override_check",
                  "mfa",
                  "model_ab_use_v2",
                  "model_switcher",
                  "new_plugin_oauth_endpoint",
                  "paragen_mainline_alternative",
                  "plugins_available",
                  "privacy_policy_nov_2023",
                  "shareable_links",
                  "starter_prompts",
                  "targeted_replies",
                  "thumbs_down_only",
                  "use_o11y",
                  "user_settings_announcements"
              ],
              "entitlement": {
                  "subscription_id": "e5833ba0-ec68-xxxx-xxxx-a221eb5e6c37",
                  "has_active_subscription": false,
                  "subscription_plan": "chatgptplusplan",
                  "expires_at": "2024-01-29T20:56:58+00:00",
                  "billing_period": null
              },
              "last_active_subscription": {
                  "subscription_id": "e5833ba0-ec68-xxxx-xxxx-a221eb5e6c37",
                  "purchase_origin_platform": "chatgpt_web",
                  "will_renew": false
              },
              "is_eligible_for_yearly_plus_subscription": false
          }
      },
      "account_ordering": [
          "5ea18f8d-9e19-xxxx-xxxx-14777052ec60",
          "0d1b6707-3119-xxxx-xxxx-596c869db2cd"
      ]
  }
  ```
</details>

**Comment by IlyaRice** [comment] 2024-04-29 03:47
Yeah, works like a charm. Thank you!

**Comment by pionxzh** [comment] 2024-04-29 03:53
Nice~

**Closed by pionxzh** 2024-04-29 03:53 UTC
Labels: bug
