### ISSUE TITLE
Exporter is not working after 2.0 release

### ISSUE THREAD

**Issue by Amie-chan** [pionxzh/chatgpt-exporter#68] opened 2023-03-07 21:01 UTC
Or it takes an extremely long time.

Downgrading back to 1.9.1 worked immediately

---

## Words from maintainer
`v2.1.1` has been released to rollback the plugin to `1.9.1`.

We rewrote the plugin to use the API provided by ChatGPT for providing richer features. (See #64)
However, the history API has been temporarily disabled by OpenAI.
We will continue to work on this plugin and release a new version when the API is available again.

**Comment by pionxzh** [comment] 2023-03-08 01:55
Hi @Amie-chan, I have a few questions to check with you.

1. Is it a long document?
2. Do you have more than 20 existing chat history?
3. Does this also happened on text and markdown?

**Comment by pionxzh** [comment] 2023-03-08 01:57
Hi @Amie-chan, I have a few questions to check with you.

1. Is it a long document?
2. Do you have more than 20 existing chat history?
3. Does this also happened on text and markdown?
4. Take extremely long...Like how long?

**Comment by Amie-chan** [comment] 2023-03-08 02:30
1. Tried both long (4 scroll pages worth), and short (single reply) with same results
2. No, <10
3. I only tried screen cap and it works, I can try the others later
4. >10 minutes with no result
5. No

The html generation worked within 2s after downgrading, using the same conversation

**Comment by pionxzh** [comment] 2023-03-08 03:13
Can you see your history? Seems like history API has been disabled for an unknown reason.

**Comment by pionxzh** [comment] 2023-03-08 03:40
We will have to wait for the history module back.
I will add an enhancement on the UI to let user know what happened and why.

![image](https://user-images.githubusercontent.com/9910706/223613697-cbcb5a62-e32e-485f-b93f-a56ad99a350c.png)

**Comment by Amie-chan** [comment] 2023-03-08 03:49
I cannot see the history. It was available earlier today when I submitted the issue

**Comment by pionxzh** [comment] 2023-03-08 04:27
> I cannot see the history. It was available earlier today when I submitted the issue

The script itself also has a bug here. I will fix it.

**Comment by pionxzh** [comment] 2023-03-08 05:52
This
![image](https://user-images.githubusercontent.com/9910706/223630537-6855cb49-1acc-4bdb-9cf0-a6b31d301f7e.png)

**Comment by pionxzh** [comment] 2023-03-08 05:56
And I'm considering bringing some local parsing back as a fallback.

**Comment by pionxzh** [comment] 2023-03-08 06:01
[v2.1.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.1.0) has been released. But it will **not** fix the problem. It can only reflect the actual situation properly.

If you really want to use the export feature, then downgrading to 1.9.1 is also a solution.

**Comment by pionxzh** [comment] 2023-03-08 14:41
Well... it gets weird now. They unlocked the history feature toggle... but you will get an empty history list from the API.

```js
window.__NEXT_DATA__.props.pageProps.shouldDisableHistory // false
```

**Comment by alex-rosenberg35** [comment] 2023-03-08 15:06
Ditto, I concur.

**Comment by alex-rosenberg35** [comment] 2023-03-08 15:07
I suggest renaming this issue to avoid duplicates. The name is misleading as this affects all export capability.

**Comment by alex-rosenberg35** [comment] 2023-03-08 15:12
Thanks @pionxzh for your excellent work on this btw! I can confirm v1.9.1 works.

**Comment by pionxzh** [comment] 2023-03-08 15:17
> Thanks @pionxzh for your excellent work on this btw! I can confirm v1.9.1 works.

You can use `2.1.1`, which is equivalent to 1.9.1. 
This approach enables most of the people to stay up-to-date and still be able to get something functional.

**Comment by pionxzh** [comment] 2023-03-09 06:47
Looks like the history API is back, but now I'm away from my PC. I will put back 2.1.0 when I'm available.

**Comment by pionxzh** [comment] 2023-03-09 13:25
> You can log out and log back in, see what happens, sourced from this [reddit post](https://old.reddit.com/r/ChatGPT/comments/11lxfz3/heres_how_to_get_your_chats_back/). See what happens.

Oh wow, thanks dude 😭

**Comment by pionxzh** [comment] 2023-03-10 11:32
I'm closing this as the API is back and [v2.1.2](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.1.2) has been released.

**Closed by pionxzh** 2023-03-10 11:32 UTC
Labels: bug
